import {
    faAirbnb,
    faAmazon,
    faApple,
    faAngular,
    faBitcoin,
    faDev,
    faDocker,
    faEdge,
    faDropbox,
    faEvernote,
    faGithub,
    faGoogle,
    faGulp,
    faHtml5,
    faInstagram,
    faJs,
    faLinkedin,
    faLyft,
    faMedium,
    faPlaystation,
    faRedhat,
    faSpotify,
    faTelegram,
    faTwitter,
    faXbox,
    faYoutube
} from '@fortawesome/free-brands-svg-icons';
import {
    faBrain,
    faBug,
    faCar,
    faCloudMoon,
    faDiceSix,
    faFire,
    faFistRaised,
    faGhost,
    faGrinSquint,
    faHeartbeat,
    faHippo,
    faHeadSideCoughSlash,
    faMeteor,
    faMoon,
    faPeace,
    faRadiation,
    faRocket,
    faSkull,
    faSpaceShuttle,
    faTruckMonster,
    faVirus,
    faWifi,faQuestion

} from "@fortawesome/free-solid-svg-icons";

export const icons = [faAirbnb,
    faAmazon,
    faApple,
    faAngular,
    faBitcoin, faBrain, faBug,
    faCar,
    faCloudMoon,
    faDiceSix,
    faFire,
    faFistRaised,
    faGhost,
    faGrinSquint,
    faHeartbeat,
    faHippo,
    faHeadSideCoughSlash,
    faMeteor,
    faMoon,
    faPeace,
    faRadiation,
    faRocket,
    faSkull,
    faSpaceShuttle,
    faTruckMonster,
    faVirus,
    faWifi, faDev,
    faDocker,
    faEdge,
    faDropbox,
    faEvernote,
    faGithub,
    faGoogle,
    faGulp,
    faHtml5,
    faInstagram,
    faJs,
    faLinkedin,
    faLyft,
    faMedium,
    faPlaystation,
    faRedhat,
    faSpotify,
    faTelegram,
    faTwitter,
    faXbox,
    faYoutube,faQuestion];


